# NumPy Exercise
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

Using only NumPy, perform the following.

1. Create an array of the form $b = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$
1. Create a 2x2 array of the form $X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
1. Multiply the two arrays element wise, then using matrix multiplication, and finally the inner product of $b \bullet b$.
1. For each of your results in part (3), print the shape and data type.
1. Reshape (or flatten), the array $X$ such that it consists of only 1 row.
1. Create an array of the integers 1 to 10, inclusive, setting the datatype to float.
1. Create a 10x10 identity matrix using the built in numpy function.
1. Create a 10x10 identity matrix using a for loop.
1. Generate a set of random data, $X$, drawn from a normal distribution, consisting of 9 columns of 100 rows each, then attach a column of all ones, resulting in a 100x10 matrix for $X$.  Next generate a random array $\beta$, drawn from a uniform distribution, of length 10.  Also make an array, $\epsilon$ of length 100, drawn from a normal distribution.  Finally, compute a vector $\vec{y}$ such that $\vec{y} = X\beta + \epsilon$.  Be sure to set the random seed to 0 before drawing any random numbers.  All random numbers should be on the interval [0, 1).
1. Using the vector $\vec{y}$ computed in part 9, create a vector $\vec{c}$ containing the labels "positive" or "negative" for each value in $\vec{y}$, treating 0 as positive.  **Bonus:** Do it with a one-liner.
1. Using the classes generated in part 10, separate the matrix X into two smaller matricies, $X_p$, $X_n$, containing only rows which map to positive or negative values respectively.
1. Generate a meshgrid on the interval [0, 1], of shape 100x100.  Then compute the Euclidean Distance given by $d = \sqrt{x^2 + y^2}$ from the origin for each unit, $(x_n, y_n)$, in the grid.  **Bonus:** Do it with a one-liner.
1. Generate a set of 100 values, $p$,  on the interval $[0, 2\pi]$ and two vectors, $\vec{x}, \vec{y}$ such that $\vec{x} = cos(p)$ and $\vec{y} = sin(p)$.  Then compute the vector $\vec{r} = \sqrt{x^2 + y^2}$.  Comment on your results.
1. Generate two lists, `a`, `b`, consisting of 10 randomly drawn values from a normal and uniform distribution respectively.  Compute the mean and median of each.
1. Using `a` from part 14, create a new list `c` by calling `a = c`.  Now change the shape of `c`.  Comment on your results.
1. How would you solve the problem that appeared in part 15?

In [1]:
import numpy as np

In [19]:
# part 1
b = np.array([1, 2])
b

array([1, 2])

In [20]:
# part 2
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [21]:
# part 3
# Element-wise
y1 = b * X
print(y1)

[[1 4]
 [3 8]]


In [22]:
# Matrix multiplication
y2 = np.matmul(b, X)
print(y2)

[ 7 10]


In [23]:
# Inner product of b
y3 = np.inner(b, b)
print(y3)

5


In [25]:
# part 4
print(y1.dtype, y1.shape)
print(y2.dtype, y2.shape)
print(y3.dtype, y3.shape)

int64 (2, 2)
int64 (2,)
int64 ()


In [28]:
# part 5
X.reshape(1, 4)

array([[1, 2, 3, 4]])

In [30]:
# part 6
a = np.arange(1, 11, dtype='float')
print(a)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [31]:
# part 7
i = np.eye(10)
print(i)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [36]:
# part 8
I = []
for i in range(10):
    row = [0] * 10
    for j in range(10):
        if i == j:
            row[j] = 1
    I.append(row)
    
I

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

In [52]:
# part 9
X = np.random.randn(100, 9)
ones = np.ones((100, 1))

X = np.hstack((X, ones))
beta = np.random.rand(10)
ep = np.random.randn(100)

y_vec = np.matmul(X, beta) + ep

print(y_vec)

[ -2.07191192e+00   8.26404275e-01   3.08951410e+00   1.79363754e+00
  -1.55083977e-01  -1.45322874e+00   6.27011621e-01  -8.39289815e-01
   1.88752558e+00   4.78077914e+00   1.10691597e+00   7.65578333e-01
   1.20020907e+00   9.24952019e-01   3.95477604e+00  -3.93726237e-01
   6.08075757e-01   1.62958027e+00   1.20874055e-01   1.92762825e+00
  -5.75849924e-01   6.03047046e-01   3.42850339e+00  -1.81398464e+00
   2.47877739e+00   2.72925992e+00  -1.02362515e+00   5.64383161e-01
   1.41293504e+00   5.27903802e+00  -2.43119529e-01   1.68872594e-02
   3.77000782e+00  -2.51229787e+00  -7.04491636e-01  -1.13099876e-01
  -8.59674364e-01   1.30450122e+00   7.87917306e-01   4.03440846e+00
   2.61085312e+00   3.44762358e+00   1.78091337e+00   6.52348541e-02
  -7.57782272e-01   7.08309329e-01   1.04107211e+00   2.79413340e-01
   1.64510089e+00  -1.23728430e+00  -7.15501091e-01   2.20365499e+00
   4.17426032e+00  -1.39682450e+00   4.15870619e-01   9.48746159e-01
   3.16126658e+00  -2.77125713e+00

In [61]:
# part 10
c_vec = ['positive' if val >= 0 else 'negative' for val in y_vec]

In [69]:
# part 11
c_vec = np.array(c_vec)
Xp = X[c_vec == 'positive']
Xn = X[c_vec == 'negative']

In [70]:
# part 12
xx, yy = np.meshgrid(np.linspace(0, 1, 100), np.linspace(0, 1, 100))

d = []
for i in range(100):
    for j in range(100):
        d.append(np.sqrt(xx[i, j]**2 + yy[i, j]**2))
        
d = [np.sqrt(xx[i, j]**2 + yy[i, j]**2) for i in range(100) for j in range(100)]

In [74]:
# part 13
p = np.linspace(0, 2*np.pi, 100)
x = np.cos(p)
y = np.sin(p)

r = np.sqrt(x**2 + y**2)
r

# The result is simply an array of 100 1s

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
# part 14
norm = np.random.randn(10)
uni = np.random.rand(10)

print('Normal dist mean: ', np.mean(norm))
print('Normal dist median: ', np.median(norm))
print('Uniform dist mean: ', np.mean(uni))
print('Uniform dist median: ', np.median(uni))


Normal dist mean:  -0.223138304935
Normal dist median:  -0.394292060332
Uniform dist mean:  0.458940640573
Uniform dist median:  0.475621065963


In [94]:
# part 15
c = norm
c.shape = (5,2)
norm

array([[-1.54774807, -1.28539727],
       [ 1.74484292,  0.11826392],
       [-0.10023402, -0.60520186],
       [-0.18338226, -0.89011285],
       [ 1.6452823 , -1.12769586]])

In [96]:
# part 16
a = np.arange(10)
c = a.copy()

c.shape = (5, 2)

print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
